// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package hudi

import (
	"bufio"
	"bytes"
	"fmt"
	"strings"
)

// Property keys used in a Hudi table's .hoodie/hoodie.properties file.
const (
	PropTableName         = "hoodie.table.name"
	PropTableType         = "hoodie.table.type"
	PropTableVersion      = "hoodie.table.version"
	PropBaseFileFormat    = "hoodie.table.base.file.format"
	PropPartitionFields   = "hoodie.table.partition.fields"
	PropRecordKeyFields   = "hoodie.table.recordkey.fields"
	PropKeyGeneratorClass = "hoodie.table.keygenerator.class"
	PropPrecombineField   = "hoodie.table.precombine.field"
	PropChecksum          = "hoodie.table.checksum"
	PropTableSchema       = "hoodie.table.schema"
)

// TableProperties represents parsed key-value pairs from .hoodie/hoodie.properties.
type TableProperties struct {
	Properties map[string]string
}

// NewTableProperties initializes a TableProperties map.
func NewTableProperties() *TableProperties {
	return &TableProperties{
		Properties: make(map[string]string),
	}
}

// ParseProperties parses java .properties format bytes.
func ParseProperties(data []byte) (*TableProperties, error) {
	props := NewTableProperties()
	scanner := bufio.NewScanner(bytes.NewReader(data))

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "!") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			k := strings.TrimSpace(parts[0])
			v := strings.TrimSpace(parts[1])
			props.Properties[k] = v
		}
	}

	return props, scanner.Err()
}

// Serialize serializes properties into standard Java .properties format.
func (p *TableProperties) Serialize() []byte {
	var buf bytes.Buffer
	buf.WriteString("# Generated by polytable\n")
	for k, v := range p.Properties {
		fmt.Fprintf(&buf, "%s=%s\n", k, v)
	}
	return buf.Bytes()
}

// Get returns the value for key or empty string.
func (p *TableProperties) Get(key string) string {
	return p.Properties[key]
}

// Set sets the value for key.
func (p *TableProperties) Set(key, value string) {
	p.Properties[key] = value
}
